use std::sync::Arc;
use std::time::Instant;

use oc_sidememory::sidememory::ImportedMemory;

use crate::clock::Clock;
use crate::deadline::Deadline;
use crate::engine::EngineSession;
use crate::error::{ErrorCode, GateError, GateResult};
use crate::registry::ToolSpec;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SamplingMode {
    Greedy,
    Seeded(u64),
}

#[derive(Clone, Debug)]
pub struct GenerationConfig {
    pub model_width: usize,
    pub eos_id: u32,
    pub vocabulary_digest: String,
    pub max_new_tokens: usize,
    pub max_rollback: usize,
    pub sampling: SamplingMode,
    pub finite_logits: bool,
}

impl GenerationConfig {
    pub fn exact(spec: &ToolSpec) -> Self {
        Self {
            model_width: spec.artifact.model_width(),
            eos_id: spec.artifact.eos_token_id(),
            vocabulary_digest: spec.vocabulary_digest.clone(),
            max_new_tokens: 1024,
            max_rollback: 32,
            sampling: SamplingMode::Greedy,
            finite_logits: true,
        }
    }
}

#[derive(Clone, Debug)]
pub struct Generated {
    pub bytes: Vec<u8>,
    pub committed_tokens: Vec<u32>,
    pub mask_ns: Vec<u64>,
    pub selection_ns: Vec<u64>,
    pub advance_ns: Vec<u64>,
}

pub struct GuideSession {
    engine: EngineSession,
    spec: Arc<ToolSpec>,
    config: GenerationConfig,
    mask: Vec<u32>,
}

impl GuideSession {
    pub fn new(
        spec: Arc<ToolSpec>,
        imports: Option<Arc<ImportedMemory>>,
        config: GenerationConfig,
    ) -> GateResult<Self> {
        if config.model_width != spec.artifact.model_width()
            || config.eos_id != spec.artifact.eos_token_id()
            || config.vocabulary_digest != spec.vocabulary_digest
        {
            return Err(GateError::new(
                ErrorCode::VocabMismatch,
                "model vocabulary, EOS, or fingerprint differs from artifact",
            ));
        }
        let engine = spec.artifact.start_session(imports, config.max_rollback)?;
        let mask = vec![0; engine.mask_word_count()];
        Ok(Self {
            engine,
            spec,
            config,
            mask,
        })
    }

    pub fn generate_target(&mut self, target: &[u8]) -> GateResult<Generated> {
        self.generate_target_inner(target, None)
    }

    pub fn generate_target_until(
        &mut self,
        target: &[u8],
        clock: &dyn Clock,
        deadline: Deadline,
    ) -> GateResult<Generated> {
        self.generate_target_inner(target, Some((clock, deadline)))
    }

    fn generate_target_inner(
        &mut self,
        target: &[u8],
        deadline: Option<(&dyn Clock, Deadline)>,
    ) -> GateResult<Generated> {
        let mut bytes = Vec::with_capacity(target.len());
        let mut committed_tokens = Vec::with_capacity(target.len());
        let mut mask_ns = Vec::with_capacity(target.len());
        let mut selection_ns = Vec::with_capacity(target.len());
        let mut advance_ns = Vec::with_capacity(target.len());
        let mut offset = 0usize;
        let mut rng = match self.config.sampling {
            SamplingMode::Greedy => 0,
            SamplingMode::Seeded(seed) => seed,
        };

        for _ in 0..self.config.max_new_tokens {
            if let Some((clock, deadline)) = deadline {
                deadline.check(clock)?;
            }
            if offset == target.len() {
                break;
            }
            let started = Instant::now();
            self.engine.write_mask(&mut self.mask)?;
            mask_ns.push(elapsed_ns(started));
            if !self.mask.iter().any(|word| *word != 0) {
                return Err(GateError::new(
                    ErrorCode::EmptyMask,
                    "guide has no continuation",
                ));
            }
            let started = Instant::now();
            let token = self.select_target_token(&target[offset..], &mut rng)?;
            selection_ns.push(elapsed_ns(started));
            let token_bytes = self
                .spec
                .vocabulary
                .spec()
                .token_bytes(token)
                .ok_or_else(|| GateError::new(ErrorCode::VocabMismatch, "token bytes missing"))?;
            let started = Instant::now();
            self.engine.advance(token)?;
            advance_ns.push(elapsed_ns(started));
            bytes.extend_from_slice(token_bytes);
            committed_tokens.push(token);
            offset = offset.checked_add(token_bytes.len()).ok_or_else(|| {
                GateError::new(
                    ErrorCode::InternalInvariant,
                    "generated byte offset overflow",
                )
            })?;
        }
        if offset != target.len() {
            return Err(GateError::new(
                ErrorCode::TokenBudgetExceeded,
                "generation token limit reached",
            ));
        }
        if !self.engine.is_accepting()? {
            return Err(GateError::new(
                ErrorCode::NotAccepting,
                "generated sequence is not accepting",
            ));
        }
        if bytes != target {
            return Err(GateError::new(
                ErrorCode::InternalInvariant,
                "guide and output traces diverged",
            ));
        }
        Ok(Generated {
            bytes,
            committed_tokens,
            mask_ns,
            selection_ns,
            advance_ns,
        })
    }

    fn select_target_token(&self, remaining: &[u8], rng: &mut u64) -> GateResult<u32> {
        if !self.config.finite_logits {
            return Err(GateError::new(
                ErrorCode::NoFiniteAllowedLogit,
                "all allowed logits are non-finite",
            ));
        }
        let mut selected = None;
        let mut matches = 0u64;
        for (id, token_bytes) in self.spec.vocabulary.spec().entries() {
            if is_allowed(&self.mask, id) && remaining.starts_with(token_bytes) {
                matches = matches.checked_add(1).ok_or_else(|| {
                    GateError::new(ErrorCode::InternalInvariant, "candidate count overflow")
                })?;
                match self.config.sampling {
                    SamplingMode::Greedy => {
                        if selected.is_none_or(|current| id < current) {
                            selected = Some(id);
                        }
                    }
                    SamplingMode::Seeded(_) => {
                        *rng = xorshift(*rng);
                        if *rng % matches == 0 {
                            selected = Some(id);
                        }
                    }
                }
            }
        }
        selected.ok_or_else(|| {
            GateError::new(
                ErrorCode::TokenRejected,
                "target token is outside the selected engine mask",
            )
        })
    }

    pub fn engine_mut(&mut self) -> &mut EngineSession {
        &mut self.engine
    }

    pub fn is_accepting(&mut self) -> GateResult<bool> {
        self.engine.is_accepting()
    }

    #[must_use]
    pub fn spec(&self) -> &ToolSpec {
        &self.spec
    }

    #[must_use]
    pub fn mask_capacity_words(&self) -> usize {
        self.mask.capacity()
    }
}

fn is_allowed(mask: &[u32], id: u32) -> bool {
    let word = usize::try_from(id / 32).ok();
    word.and_then(|word| mask.get(word))
        .is_some_and(|value| value & (1u32 << (id % 32)) != 0)
}

fn xorshift(mut value: u64) -> u64 {
    if value == 0 {
        value = 0x9e37_79b9_7f4a_7c15;
    }
    value ^= value << 13;
    value ^= value >> 7;
    value ^ (value << 17)
}

fn elapsed_ns(started: Instant) -> u64 {
    u64::try_from(started.elapsed().as_nanos()).unwrap_or(u64::MAX)
}
